Resources:
  createProductTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: notify-about-products

  createProductTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: testemail88888888888888888888@gmail.com
      Protocol: email
      FilterPolicy:
        title:
          - "BMW 4-series"
      TopicArn:
        Ref: createProductTopic

  createProductTopicSubscriptionForAnotherTitle:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: testemail9999999999999999999@gmail.com
      Protocol: email
      FilterPolicy:
        title:
          - "BMW 2-series"
      TopicArn:
        Ref: createProductTopic
